### ISSUE TITLE
Beyond Earth (Space boss tools), Can't Respawn with UI

### ISSUE THREAD

**Issue by graceospaceo** [LunaPixelStudios/Better-Minecraft-PLUS#1]
Using the new Space Boss Tools mod, I built a rocket went to the moon and mars successfully. I built the third-tier rocket to go to Venus and while in the air it lets you decide where to go and while deciding i fell out of the rocket and died and now my screen is flashing between respawn and pick where to go and neither will work. Is there a way to fix or bypass this or am I permanently stuck?

**Comment by switchnlade** [comment]
Oops, meant that for another issue, testing this now

**Comment by switchnlade** [comment]
So, this is a massive issue purely on Space Boss Tools, I'll report it to the dev. Only fix I can figure out is deleting it from your mods folder, loading without it and respawning, and adding it in again. Essentially even on a relog, the UI still glitches out so there's nothing to really be done to circumvent it besides that. Once you do that, and it's worked out, please close the issue.

So overall: Remove space boss tool, relog and respawn, add it back in. Do not dismount the rocket on the planet selection screen.

**Comment by SharkieTV** [comment]
Also Beyond Earth (Space boss tools) will be removed in next version to due causing Crashing in the Overworld and more.

**Comment by SharkieTV** [comment]
Mod will be removed in next update to other issues.

**Comment by graceospaceo** [comment]
I don't see Space Boss tools or Beyond Earth in my mods folder, is it a different name?

**Comment by graceospaceo** [comment]
Okay I deleted it and now it says the connection was forcibly closed by host whenever I try to join.

**Comment by switchnlade** [comment]
Can you upload the server latest.log and the client's latest.log? Make sure it's from the failed attempt to join so if you have to start the server up once more just for it, please do.

**Comment by graceospaceo** [comment]
Hi idk know what that means. Can you explain to me how to do that? Thank you

**Comment by switchnlade** [comment]
Inside the main server folder, there will be a folder titled 'logs'. Inside that will contain a file called 'lastest.log', open it and copy/paste it into a site like [pastebin.](https://pastebin.com/) Once you do that, post the link in here so we can see it.
This is pretty much the same on the client, but it's instead in the client's 'logs' folder. If you use CurseForge, you can right click on the modpack in the my modpacks screen and click open folder to get to it. If on GDLauncher, you can do the same right click on the modpack, and click open folder, and it will open the client folder.

**Comment by graceospaceo** [comment]
It says the file is too big to paste into pastebin.

**Comment by graceospaceo** [comment]
Okay I think I got it. Here is the latest log: https://gist.github.com/graceospaceo/2e2b44a3ebe8e4af114680550c3c71c9
and here is the client log: https://gist.github.com/graceospaceo/5a07334641594d769ef28199967dece6 


I dont think I did the client log right. Also I think its important to mention I had uninstalled the Space Boss Tools mod like asked to and then I tried to reinstall it.

**Comment by switchnlade** [comment]
Right, not too sure what happened exactly, let's not worry about the logs, can you try updating to v36. See if this fixes the issue, outside of that, I don't have an idea. It seems like whatever that mod did really made a mess of things.

**Comment by graceospaceo** [comment]
I updated it, it says no connection with a red X. ):

**Comment by graceospaceo** [comment]
Finally! i was able to log in, thank you for your help.
