### ISSUE TITLE
Server client version mismatch

### ISSUE THREAD

**Issue by ArmandAgopian** [LunaPixelStudios/Better-Minecraft-PLUS#10]
### Describe the Bug

Better compatibility checker lists clientside modpack version as v36.5 even after installing v37, failing compatibility check for server. Client can still connect, however. Both fresh installs.

### Reproduction Steps

1. Install v37 both client and server
2. Try to connect to server
3. Compatibility checker fails

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v37

### Optifine

No

**Comment by SharkieTV** [comment]
Seems like I forgot to update the Client Version, will update this when new version comes out
