### ISSUE TITLE
crash :[

### ISSUE THREAD

**Issue by channelRED** [LunaPixelStudios/Better-Minecraft-PLUS#11]
### Describe the Bug

When I create a new world, it proceeds as normal but then the loading completely stops. The image that's generally right  below the percentage continues growing, and the tips continue to flash by, but I never get to enter my new world. It stays there indefinitely.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://paste.ee/p/3mLss

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v37

### Optifine

No

**Comment by switchnlade** [comment]
Remove ore stone variants (osv) from the mods folder
