### ISSUE TITLE
Please please stop with the fullscreen

### ISSUE THREAD

**Issue by The-Professor123** [LunaPixelStudios/Better-Minecraft-PLUS#12]
### Describe the Bug

there are no bugs as far as functionality is concerned. just please for the love of gaming don't force fullscreen. its annoying and it comes across as attention seeking (if a game can come across as such). again: I love the pack. nothing wrong with how it was made. except the fullscreen. at bare minimum I would appreciate making the fullscreen button in video settings work.

### Reproduction Steps

1. launch the game 
2. wait
3.
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v38

### Optifine

No

**Comment by switchnlade** [comment]
It's not forced? I can change between full and windowed with ease, both with the video settings option and by pressing f11 (shortcut for fullscreen/windowed switch). Unless you meant the default load state? Also full screen is not attention seeking, it's how games are meant to be played, hence why just about all other games use full screen as the default option.

**Comment by SharkieTV** [comment]
Not sure how it comes as attention seeking lmao? If you have any video game knowledge you would know you can press F11 or Alt + Enter to go out and in of full screen and that Full screen provides the best performance. Again not sure how this is "Attention Seeking". And you saying the setting to change to windowed doesn't work but it does?
