### ISSUE TITLE
Exit code -1

### ISSUE THREAD

**Issue by Electricurmom** [LunaPixelStudios/Better-Minecraft-PLUS#14]
### Describe the Bug

when i load into the world it simply give me exit code -1 i havnt played it before

### Reproduction Steps

1.open the game
2.make world
3.load world
4.exit code -1

### Operating System

windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v38

### Optifine

I used Optifine

### Other Mods

Tluncher skin loader

**Comment by SharkieTV** [comment]
You are using TLauncher?

**Comment by Electricurmom** [comment]
> You are using TLauncher? Does that also mean you are using Cracked?

Minecraft mojang account on Tluncher i use it cuz making modpacks is easy on it

**Comment by switchnlade** [comment]
So you own an account? Quit using an illegal launcher then. It does not make things easy, it sucks at mods. Your issue is coming from the use of TL with 99.99% certainty. Use curseforge, gdlauncher, or multimc as some examples.
