### ISSUE TITLE
Crashing upon entering newly created server 

### ISSUE THREAD

**Issue by Nineball89** [LunaPixelStudios/Better-Minecraft-PLUS#16]
### Describe the Bug

Created a new server instance, joined it on my localhost. Played for few seconds and got an crash. Happens everytime when I create new server. Tried without magnesium mod like it was suggested in the discord server, still got an crash..

Edit; Its even crashed on single player world after few minutes of play. 
Uploaded singleplayer crashlog 
https://pastebin.com/MJYizaKc

### Reproduction Steps

1.Start new server/single world
2.Join your server/your single world
3.Play for a few seconds/minutes
4.Should crash

### Crash Report or Log

https://pastebin.com/wH7mreAV

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

bmc+ v38

### Optifine

No

### Other Mods

removed betteranimation mod as it was crashing for me as well.

**Comment by SharkieTV** [comment]
See if removing dungeon mobs helps

**Comment by Nineball89** [comment]
Update. I have removed dungeon mobs, created new world and started to tp all over the map to see if it will crash. So far it did not that. Should I continue to test more?

**Comment by SharkieTV** [comment]
Nah should be good now, it was a Cave Spider from Dungeons Mobs I think in the crash so yeah
