### ISSUE TITLE
Exit Code -805306369

### ISSUE THREAD

**Issue by kilian1310** [LunaPixelStudios/Better-Minecraft-PLUS#17]
### Describe the Bug

Loaded the modpack with CurseForge and I got the exit code after trying to create a new world. Can't enter this world either or create a new one. Tried multiple times. 

I'm not sure where I can find the crash log. 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

Better Minecraft Plus v.38

### Other Mods

CurseForge Modloader

**Comment by SharkieTV** [comment]
Need a Crash report or Log please

**Comment by kilian1310** [comment]
It didn't create a Crash Report (only found an old one for Better Minecraft) but I gave it a shot and allocated even more RAM to it and it worked after waiting for ~2 Min. 

Sorry for bothering and thanks for your "work"
