### ISSUE TITLE
Server does not start,

### ISSUE THREAD

**Issue by TheGreat09123** [LunaPixelStudios/Better-Minecraft-PLUS#19]
### Describe the Bug

After starting the server to download the required jars (which worked fine), the console spits out an error about the java version. (Better Minecraft PLUS 1.18.1)

### Reproduction Steps

1. Use script to download jars
2. Start server
3. It does not work.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/72113421/156954273-67584e6e-a319-4ec7-91c7-8608276598b6.png)

### Crash Report or Log

https://pastebin.com/Pwhj4TX9

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v4 NOTE: Using 1.18.1 BMC Plus

### Optifine

No

**Comment by SharkieTV** [comment]
You need Java 17 to run the server
