### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by raricat** [LunaPixelStudios/Better-Minecraft-PLUS#2]
### Describe the Bug

trying to install through curseforge and it's not working. Saying invalid profile when I tried to create custom profile with file. Can't download through curseforge either

### Reproduction Steps

1. Download file from website
2. Create custom profile with said file
3.
...

### Screenshots and Videos

![Screenshot 2022-01-13 143003](https://user-images.githubusercontent.com/97646470/149249565-54f51f83-b69d-40b8-9c96-08f52e7bf26b.png)

### Operating System

windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

 Better Minecraft [PLUS] v36.5

### Optifine

No

**Comment by switchnlade** [comment]
I'm going to mark this as just an issue that was on curseforge during their outage. Mine is downloading just fine. Please keep trying again, if all else fails, try GDLauncher or MultiMC.
