### ISSUE TITLE
chunk generation (1.18.1)

### ISSUE THREAD

**Issue by DeLay29** [LunaPixelStudios/Better-Minecraft-PLUS#20]
### Describe the Bug

World started to generate new chunks from where the minimap has rendered and did not blend. As far as I remember I did not update from v3 to v4 of 1.18.1 and it could be due to my game crashing halfway while flying in the end giving this error message:
This crash may be caused by an invalid Java Runtime configuration. Check any custom configuration settings. Exit code: 1 (could be irrelevant to the bug)

### Reproduction Steps

1.Not sure fly as far as possible in the end
2.
3.
...

### Screenshots and Videos

![2022-03-23_21 59 27](https://user-images.githubusercontent.com/31798675/159720630-f8d83299-8606-4f1a-bdc8-049e02e4b3b7.png)

### Crash Report or Log

https://pastebin.com/01j91nPZ

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

bmc plus v4

### Optifine

No

**Comment by SharkieTV** [comment]
Java Runtime configuration usually means its a System Issue and the crash yous send me is also not the correct one. You can give me your latest.log of when the latest crash happened but other than that whats your pc specs and ram allocation?

**Comment by DeLay29** [comment]
https://pastebin.com/eHm07ZWY
RTX 2070
I7-10700K
16GB RAM

Allocated 8gb

**Comment by SharkieTV** [comment]
That latsest.log doesnt say anything is wrong.
What do you mean by "I did not update from v3 to v4 of 1.18.1"?
You started a new world on v4?
Also if oyu say the  Exit code: 1 comes up after it crashes it must haver a crash in the crash report and I need the correct one in order to help.

**Comment by DeLay29** [comment]
Yeah I started a new world on v4.
A previous world I updated from v3 to v4 had the same world issue as above
https://pastebin.com/Fderpr9G
https://pastebin.com/t2kdnsCz
https://pastebin.com/nFnV3pkG
unfortunately i don't remember the exact date the crash occured (potentially happened 1 week from now, potato memory lol) and these were the latest crash reports i could find

**Comment by DeLay29** [comment]
Apparently my game crashed minutes after when i opened a barrel at this generated structure (not sure what mod it is from) and it gave me a crash report.
https://pastebin.com/7BAny08y
(again could be irrelevant to the world generation bug)
![2022-03-24_00 05 28](https://user-images.githubusercontent.com/31798675/159743820-fb3d7de3-b3f7-4cc0-84c8-62f310b4a464.png)

**Comment by SharkieTV** [comment]
So does it crash now?

**Comment by DeLay29** [comment]
it did crash on a new world (above pictures are from the new world)

**Comment by SharkieTV** [comment]
1.18.1 v4 is no longer being developed as I have moved to 1.18.2
In one of the crashes it mentions create so it can be create mod causing the issue or it is the performance mods rubidium and oculus.

**Comment by DeLay29** [comment]
Ah okay thanks

**Comment by jetcreeper8978** [comment]
hey i have a problem with the game to

**Comment by jetcreeper8978** [comment]
why dont you use this mod it might help https://www.curseforge.com/minecraft/mc-mods/ferritecore

**Comment by jetcreeper8978** [comment]
i need help with the loadding speed its so slo

**Comment by HeadHunterShiv** [comment]
> i need help with the loadding speed its so slo

please dont ask other issues in another issue.
