### ISSUE TITLE
every thing about loading 

### ISSUE THREAD

**Issue by jetcreeper8978** [LunaPixelStudios/Better-Minecraft-PLUS#21]
### Describe the Bug

i found better minecraft forge and i was so happy about it and played it but it took forever to load then found better minecraft plus  1.16.5 and it had some of my favorite mods so i was even happier yesterday i did not get it to load and i set it ruining over night and it loaded and now im trying to load a creative world and its been stuk on reading world data for and hour and the tip says something about dogs health and the computer is not the best but ive ran more mods and it ran just fine i dont know what to do -sory for the spelling errors  

### Reproduction Steps

1.loaded minecraft 
2.tryed loading land 
3. not working ?
...

### Screenshots and Videos

?

### Crash Report or Log

?

### Operating System

?

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

the latest 

### Optifine

No

### Other Mods

um i think the minecraft dingeons gear mod and heleom and i think lazyduf

**Comment by jetcreeper8978** [comment]
is there any mods that could help me with loading it faster

**Comment by HeadHunterShiv** [comment]
@jetcreeper8978 no there's no methods in my knowledge to load the game faster just allocate sufficient ram and dont click any thing not even alt+tab while the modpack is loading. This is the most efficient.
