### ISSUE TITLE
Weird music and noise 

### ISSUE THREAD

**Issue by MineTL2004** [LunaPixelStudios/Better-Minecraft-PLUS#22]
### Describe the Bug

Sometimes when we walk there is music all of a sudden for no reason 

### Reproduction Steps

1. Create a world
2. Explore the world
3. Sometimes music for nothing
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

Better MC PLUS v38

### Optifine

I used Optifine

### Other Mods

No

**Comment by SharkieTV** [comment]
Its from the Sophisticated Backpacks mod, disable the jukebox in the config for it

**Comment by MineTL2004** [comment]
Thanks you
