### ISSUE TITLE
Can't add any more mods on a server

### ISSUE THREAD

**Issue by GefahrVonRechts** [LunaPixelStudios/Better-Minecraft-PLUS#23]
### Describe the Bug

I wanted to add some more mods i like on my server. But as soon as i add just one mod i cant join on the server anymore and get this message: "connection closed mismatched mod channel list".
The first time i only added the ProjectE mod and it didnt work. Afterwards i tried if with refined storage and i ran into the same problem.

### Reproduction Steps

1. Created a Server with the modpack
2. Tested if the Server was working without any additional mods
3. Stopped the Server
4. Added ProjectE mod to the mods folder on the server and to the mods folder on my client
5. Started the Server
6. Cant join with the message "connection closed mismatched mod channel list"

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

bmc plus v38

### Optifine

No

**Comment by SharkieTV** [comment]
connection closed mismatched mod channel list means you need to added it to the server and client otherwise you cant join but this is not an issue with the pack at all
