### ISSUE TITLE
Tide trident transforms to normal trident after being thrown.(Fire and Ice mod)

### ISSUE THREAD

**Issue by Broreally** [LunaPixelStudios/Better-Minecraft-PLUS#25]
### Describe the Bug

I enchancted a tide trident and threw it and when it came back it turned into a normal trident. I thought it was some weird glitch and to fix I could just leave the game and rejoin but that didnt work. So i made a tide trident without enchaments. I threw that one and picked it up and it did the same thing. I also closed minecraft and curseforge and reopened it but it still didn't do anything.

### Reproduction Steps

1.Go on a survival world and craft a tide trident.
2.Then throw it and pick it up.
3.
...

### Operating System

windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v38

### Optifine

No

### Other Mods

Vampirism, Werewolves, simple planes, ars nouveau, falling trees, backpacked, scorpions, magitek mechs, iron chest, and dungeons mod, dragon mounts legacy, and brass amber battle tower.

**Comment by SharkieTV** [comment]
please remove your added mods and see if the issue persists

**Comment by Broreally** [comment]
> 
Okay I did it and tested it out and the problem still continues even with all the mods I added removed.
