### ISSUE TITLE
Consistent Nether Crashing

### ISSUE THREAD

**Issue by TheRKLOPP** [LunaPixelStudios/Better-Minecraft-PLUS#26]
### Describe the Bug

The game crashed whilst tesselating liquid in world
Error: java.util.ConcurrentModificationException: null
Exit Code: -1

I have no idea what's causing all this crashing. Every few minutes in the nether causes my game to crash to desktop. nothing specific seems to cause it, but this most recent crash seems to be caused by liquids in the world? Too much lava maybe? Its been crashing frequently, and this time I turned all the settings down, at it crashed faster, in 20 seconds or so.

### Reproduction Steps

1. Start up Minecraft
2. Load into world
3. Walk around for more than 5 minutes
4. Mine anything in the environment

### Crash Report or Log

https://pastebin.com/FtTWYcH6

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

Better minecraft plus V38

### Optifine

No

**Comment by SharkieTV** [comment]
See if removing lambdynlights mod helps
