### ISSUE TITLE
Abyss 2.0 doesn’t work

### ISSUE THREAD

**Issue by dkuflu** [LunaPixelStudios/Better-Minecraft-PLUS#3]
### Describe the Bug

In Abyss 2.0, you need to be teleported to dreaming dimension when you sleep. However, this isn’t working for me. I alao didn’t receive the Abyss Guide Book after creating the world.

### Reproduction Steps

1. Open the game
2. Create new world
3. Sleep

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v36.5

### Optifine

No

### Other Mods

No. Just Better Minecraft [PLUS]

**Comment by SharkieTV** [comment]
Yeah sorry I need to fix the quest, It is meant not to go to the dream dimensions or radio dimension. The Void worm quest should give all the items to go to the dimension but I forgot to add the activator to the quest.

**Comment by dkuflu** [comment]
Glad to hear that it’s a quick fix. I’ll be waiting for v37 then. Should I close this?

**Comment by dkuflu** [comment]
Also, what about the guide book? Do I get it from the Void Worm quest as well?

**Comment by SharkieTV** [comment]
yeah all the things you need will be im the void worm quest
