### ISSUE TITLE
Chunk Not Loading

### ISSUE THREAD

**Issue by GiraffaSpotify** [LunaPixelStudios/Better-Minecraft-PLUS#30]
### Describe the Bug

When i log in my minecraft world, chunk are not loading, i can't open chests or anything, game is just frozen.
Firstly i was in the end dimension, and everything was fine until i tried to teleport to the overworld using a waystone and the world would start not loading chunks, i waited up to 10 minutes but nothing happened, i couldn't even close the game, had to do it from task manager. Had used teleport from waystones many times to travel from end to other worlds, this was the first time it happened. And it happens only to this world as if the world got corrupted for no reason, i tried to create new worlds to replicate the bug, it doesnt happen. I also tried to dedicate 14 gb of ram to minecraft without any success. So now everytime i open my world i find myself stuck in here without being able to interact with anything because chunks won't load and game is frozen.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

https://prnt.sc/HsIl0JUh-ptZ

### Crash Report or Log

https://paste.ee/p/kCR2A

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

Better Minecraft Plus v38

### Optifine

No

### Other Mods

No

**Comment by SharkieTV** [comment]
Can you allocate more ram? can you also remove Immersive FX?
