### ISSUE TITLE
Create Pondering does not show the 3d models

### ISSUE THREAD

**Issue by nonchip** [LunaPixelStudios/Better-Minecraft-PLUS#31]
### Describe the Bug

When "pondering" a Create structure (by e.g. pressing `[W]` in JEI), it shows a nice slideshow animation of how it works, but in this modpack the 3d models of the actual structure are invisible.

**NOTE!** I had to select the *only available* Minecraft Version 1.16, despite the actual one in the modpack being **1.18.2**

### Reproduction Steps

1. search for e.g. `@create crafter` in JEI
2. hover over `create:mechanical_crafter`
3. hold `[W]` for a few seconds

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/601018/166146255-f8c8d87c-004f-44c0-999f-93b24858b457.png)

### Operating System

Linux

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v8

### Optifine

No

**Comment by SharkieTV** [comment]
will be fixed in next update, update rubidium and oculus if you want it to be fixed

**Comment by nonchip** [comment]
also probably related:
![image](https://user-images.githubusercontent.com/601018/166147001-8d5f09b8-24e4-4a75-8499-e7bd58cdd71a.png)

will try the update and tell you if that fixed too :)

**Comment by nonchip** [comment]
@SharkieTV yup that did it, thanks :)
