### ISSUE TITLE
Leafcutter Ants spawn infinitely (fix suggestion)

### ISSUE THREAD

**Issue by nonchip** [LunaPixelStudios/Better-Minecraft-PLUS#32]
see also [multiple](https://github.com/Alex-the-666/AlexsMobs/issues/839) upstream [issues](https://github.com/Alex-the-666/AlexsMobs/issues/963).

long story short: the anthill keeps track of how many ants are *stored inside* it, but not how many it *spawned*, so it just keeps indefinitely replenishing the "inside list" when ants are outside, which then also get spawned, replenishing the list, getting spawned, rinse and repeat. ([technical details](https://github.com/Alex-the-666/AlexsMobs/issues/839#issuecomment-1114501616))

![image](https://user-images.githubusercontent.com/601018/166189117-5c8234fa-7072-4713-83e4-0046a8b4ceaa.png)

my suggestion for a quick workaround until @Alex-the-666 can take care of this issue (it's been known since at least January, i have to assume they're otherwise busy) would be this CraftTweaker script:
```js
import crafttweaker.api.events.CTEventManager;
import crafttweaker.api.event.entity.EntityJoinWorldEvent;
import crafttweaker.api.event.living.LivingUpdateEvent;
import crafttweaker.api.entity.Entity;
import crafttweaker.api.util.math.BlockPos;
// Every time an Entity "joins" (spawns) the World...
CTEventManager.register<crafttweaker.api.event.entity.EntityJoinWorldEvent>((event) => {
	val level = event.world;
	var range = 64;
	var nospawnNumber = 20 as usize;
	var cullingNumber = 25 as usize;
	// If it's an Ant...
	if event.entity.getType() == <entitytype:alexsmobs:leafcutter_ant> {
		var pos1 = new BlockPos(event.entity.blockX-range, event.entity.blockY-range, event.entity.blockZ-range);
		var pos2 = new BlockPos(event.entity.blockX+range, event.entity.blockY+range, event.entity.blockZ+range);
		// Get all Ants in the 64 block range...
		var ents = level.getEntities(event.entity, pos1.x, pos1.y, pos1.z, pos2.x, pos2.y, pos2.z, e => e.getType() == <entitytype:alexsmobs:leafcutter_ant>);
		// if there are more than 20...
		if(ents.length > nospawnNumber){
			// don't allow it to "join"
			event.cancel();
		}
		// if there are more than 25...
		if(ents.length > cullingNumber){
			// kill them all
			for ent in ents {
				ent.kill();
			}
		}
	}
});
```
`range = 64` seems to work for me, but keep in mind this would still require `nospawnNumber`/`cullingNumber` of spawned ants inside a 64block "radius" cube for it to trigger. if they wander further than the `range` they can still multiply. but on the other hand if the `range` is too big, it would probably impact performance looking for entities.

the "correct" way of dealing with this would obviously be a second list to track the spawned ones, but that might be non-trivial to implement in CT given a lot of things can happen to entities to invalidate those list members (unloading, dying, ...) and we'd need to keep track of all that to prevent leaking memory. for a workaround until @Alex-the-666 can properly fix this the above script feels "good enough" (works in my world™)

**Comment by SharkieTV** [comment]
Thanks will try to add this next update
