### ISSUE TITLE
Placing a redstone link pair from create in the same chunk bugs out the lighting 1.18.2

### ISSUE THREAD

**Issue by ProvoGo** [LunaPixelStudios/Better-Minecraft-PLUS#34]
### Describe the Bug

THIS IS IN 1.18.2 NOT 1.16

Made a report on the create github, do tell if you want me to make it fully here as well, for now i'm just leaving a link
https://github.com/Creators-of-Create/Create/issues/3068

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

bmc+ v11

### Optifine

No

**Comment by SharkieTV** [comment]
This is either an issue with Dynamic Lights or Oculus im assuming. Are you using shaders? can you see if removing Dynamic Lights Reforged works?

**Comment by ProvoGo** [comment]
Removing dynamic lights reforged doesn't work.
Removing that and oculus doesn't work either.
And i'm not using any shaders.

**Comment by ProvoGo** [comment]
TropheusJ said this, and i had the same result/when i removed radon the chunk light was back to normal

This is an issue with Phosphor. BMC+ 1.18.2 contains a forge port for it, but it applies to both platforms: https://github.com/CaffeineMC/phosphor-fabric/issues/82
For now, you could remove Phosphor/Radon.

**Comment by SharkieTV** [comment]
Thanks for the report
