### ISSUE TITLE
The Abyss no recipe for Unstable Obsidian (Server)

### ISSUE THREAD

**Issue by FaneTheHyena** [LunaPixelStudios/Better-Minecraft-PLUS#36]
Hello Playing on a Server with Friends and there is no Recipe for Unstable Obsidian and after i looked it up online i tried crafting it myself welp did not matter it wont work anyway seems like it got removed and i must say its pretty sad i tried giving myself the Unstable Obsidian after i entered the Portal well guess what it crashed and i had to load a backup on the server so i can play would like to know if the issue is known or if The Abyss is just not working On a Server i did not found anyone out there having the issue i had and if you asking wheres the Server Running From  (Apex Hosting) 10 Gb Ram currently Usings Between 5 and 6  Gb would be nice if someone has an answer for me or something i could try to do to fix the issue since i would really like to explore The Abyss without switching Back to singleplayer  since it works atleast there

**Comment by Ozzi-Hero** [comment]
The Abyss has custom behaviour in LPS modpacks. Unstable Obsidian is obtained from your quest rewards.
