### ISSUE TITLE
Overworld drake 

### ISSUE THREAD

**Issue by MineTL200** [LunaPixelStudios/Better-Minecraft-PLUS#38]
### Describe the Bug

Sometimes the cry of the Overworld Drake remains blocked while going away.
The bug happened when I went down a mountain about 30 blocks.

### Reproduction Steps

1. Find Overworld Drakes
2. Get closer in Survival mode
3. As soon as he screams run in the opposite direction
4. The scream will be blocked
5. Then come back to him and the screaming will stop.

### Operating System

Windows 10 pro

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

Better MC PLUS v38

### Other Mods

None

**Comment by SharkieTV** [comment]
Thanks for the report
