### ISSUE TITLE
Biome O Plenty + Oh The Biomes You'll Go not spawning on [1.18.2]

### ISSUE THREAD

**Issue by CptToucan** [LunaPixelStudios/Better-Minecraft-PLUS#39]
### Describe the Bug

The biomes found within Biome O Plenty + Oh The Biomes You'll Go not spawning do not spawn. This issue was noted in discord and was explained to be caused by the Warden and Skulk mod that is included in the pack. Here is the extract from discord:

"I had the same biome problem someone helped me and told me it’s the mod warden and skulk you gotta have the 1.0.0 version anything above that is buggy causes biomes not to generate I was trying figure out for days and that finally helped me hopefully it helps you and anybody else with that problem also"

### Reproduction Steps

1. Use latest Better Minecraft Plus Build
2. Generate new world
3. You will not find any other biomes apart from ones in Minecraft.
...

### Operating System

Windows 10

### Minecraft Version

1.18.2

### Modloader

Forge

### Modpack Version

Better Minecraft [PLUS] v11.5 on 1.18.2

### Optifine

No

**Comment by SharkieTV** [comment]
Thanks for the report
