### ISSUE TITLE
OVS null

### ISSUE THREAD

**Issue by Sanderella1** [LunaPixelStudios/Better-Minecraft-PLUS#5]
### Describe the Bug

Currently using Better Minecraft [PLUS] 1.16.5, v. 37 in CurgeForge.

We were playing a LAN world, when we entered the nether for the first time, our world froze. It crashed and I tried rebooting the modpack. I got this message about OVS - Stone Variation mod:

java.util.concurrentmodificationexception: null

It wouldn't relaunch the game instead giving me and error for the mod not reloading in order. I removed mod to desktop and it relaunched fine, world also running still. 

Included is original crash, and relaunch crashes too. 

[crash-2022-01-23_15.54.59-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft-PLUS/files/7919655/crash-2022-01-23_15.54.59-server.txt)

[crash-2022-01-23_16.01.43-fml.txt](https://github.com/LunaPixelStudios/Better-Minecraft-PLUS/files/7919656/crash-2022-01-23_16.01.43-fml.txt)
 

### Reproduction Steps

...

### Crash Report or Log

[crash-2022-01-23_15.54.59-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft-PLUS/files/7919655/crash-2022-01-23_15.54.59-server.txt)

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v 37

### Optifine

No

**Comment by Sanderella1** [comment]
[](url
[crash-2022-01-23_16.24.07-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft-PLUS/files/7919670/crash-2022-01-23_16.24.07-server.txt)
)


..... And it crashed again. This time the cause is "Ticking World".

**Comment by SharkieTV** [comment]
Yeah its untested due to it causing so many issues and I cant test it myself.
See if removing the shretnether mod from both your modpacks helps.
