### ISSUE TITLE
Create Gantry Contraptions disappearing on multiplayer

### ISSUE THREAD

**Issue by Robertodude** [LunaPixelStudios/Better-Minecraft-PLUS#6]
### Describe the Bug

When using moving contraptions in Create, the contraption can end up disappearing after stopping movement. It is similar to the bug that happened in v35, where create deco was removed.

Server is v37
Client v37

### Reproduction Steps

1. Create a Gantry Carriage contraption, add a few linear chassis to
2. Move it down the gantry
3. When it's stopped parts of it / all of it disappear

### Screenshots and Videos

https://www.youtube.com/watch?v=FH9rFMyoF-U

### Crash Report or Log

https://pastebin.com/m5Jb1HnN

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

better minecraft plus v37

### Optifine

No

**Comment by Robertodude** [comment]
create deco is not installed on either client or server

**Comment by SharkieTV** [comment]
Sorry for late reply, I tested on my end and it seems to be working fine. Can you make sure you are using the right mods and configs? If so can you provide a video how to setup up your contraption?

**Comment by Robertodude** [comment]
No worries, I'll take a further look. I'm certain my client is correct but I will take a further look at the server. Is there an easy way to check the server or will I just have to go through all the mods one by one? 

It's definitely not the same issue as before because I am able to use conveyors without an issue now.

**Comment by Robertodude** [comment]
I wonder if it could be related to the type of chest I'm using, I'll play around later.
