### ISSUE TITLE
 a crash

### ISSUE THREAD

**Issue by hhhhhhh333** [LunaPixelStudios/Better-Minecraft-PLUS#7]
### Describe the Bug

When you start loading and enter the world, moving immediately will lead to crash, or moving just after the tp in the game will lead to crash. After deleting magnesium, the problem will be solved, but without magnesium optimization, the frame rate is too low。

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://gist.github.com/hhhhhhh333/e146e2da04f7a6e5b56e2cb268812cc3

### Operating System

10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v37

### Optifine

No

### Other Mods

no

**Comment by hhhhhhh333** [comment]
Sorry for my late reply. Thank you for your reply. My computer is a laptop, i5-9300h 16g gtx1660ti. I didn't encounter such errors when playing version 35 and 36. At that time ,two people LAN online, I was the owner of the house, and the frame rate was about 70. Recently, I had the crash error in version 37. I played alone. The map is a new version, and the magnesium mod is deleted. The frame rate is about 50, Sometimes 30 or 40。  is too bad, so I don't want to give up magnesium. Strangely, if I deliberately wait for 5 minutes at the beginning of the game loading finish, the subsequent games will not crash unless I continuously TP to different places. After I deleted magnesium, although the frame rate decreased a lot, I deliberately started moving and flying and TP as soon as I loaded it into the world. It won't crash, which makes me sad. If I can't play plus, I will be even more sad，o(╥﹏╥)o

**Comment by switchnlade** [comment]
How much of your ram is allocated?

**Comment by hhhhhhh333** [comment]
8GB

**Comment by SharkieTV** [comment]
well regardless it seems like your pc is struggling with the new version or your graphics drivers arent up to date, if updating them doesnt fix it you have to lay without it unfortunately and I would say to switch to normal forge version since you are struggling to run it
